### PR TITLE
Volt Fields can now accept promises

### PR DESCRIPTION
**Pull request by jstumbaugh**
and radio and select fields also use Volt's attribute bindings.

### CODE REVIEW

**Comment by matthew342** [comment]
rebased on current master

**Comment by matthew342** [comment]
@ryanstout Is there a problem with this or do you intend to merge? Know you've got a lot going on, just asking so I know where to base further work off of.

**Comment by ryanstout** [comment]
@matthew342 sorry, just lost track of it, let me check it out, one sec.

**Comment by ryanstout** [comment]
@matthew342 sorry, just so I'm understanding.  Where does promise support come into this?

**Comment by ryanstout** [comment]
Also, does the new select field mark the field on blur?  Thanks

**Comment by matthew342** [comment]
No prob at all. 

Sorry, this was poorly named. This adds promise support to Select and Radio controls in [select_radio_controller.rb](https://github.com/matthew342/volt-fields/blob/accept_promises/app/fields/controllers/select_radio_controller.rb) by just calling `.then` on the passed options.

Bad form, but I went ahead and merged a bunch of other additions and cleanups into this branch to make it easier for you to review and merge. Here's a summary:
- Fix Select and Radio to resolve promises passed as the options
- Fixed some funky behavior with selects on page load (don't remember the details, but these are @jstumbaugh's commits)
- Added ability to turn off automatic labeling by passing 'false' to `label` attribute.
- Added [button group](http://getbootstrap.com/components/#btn-groups) control as an alternative to `select`.
- Cleaned up README

Finally, good catch on the select field - I updated to have it call `blur` on the `change` event.

**Comment by ryanstout** [comment]
Sorry this took so long, merged.  Thanks!

**Pull request merged**
